<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7PKFCKU" failures="3" tests="7" name="BankingApp Test" time="101.846" errors="0" timestamp="04 Jul 2021 17:06:18 GMT">
  <testcase classname="com.intebanking.testCases.TC_LoginTest_001" name="loginTest" time="11.778"/>
  <testcase classname="com.intebanking.testCases.TC_LoginDDT_002" name="loginDDT" time="11.411"/>
  <testcase classname="com.intebanking.testCases.TC_LoginDDT_002" name="loginDDT" time="6.115">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.intebanking.testCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:31)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.intebanking.testCases.TC_LoginDDT_002" name="loginDDT" time="10.66"/>
  <testcase classname="com.intebanking.testCases.TC_LoginDDT_002" name="loginDDT" time="5.651">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.intebanking.testCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:31)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.intebanking.testCases.TC_LoginDDT_002" name="loginDDT" time="5.717">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.intebanking.testCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:31)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.intebanking.testCases.TC_AddCustomerTest_003" name="addNewCustomer" time="15.9"/>
</testsuite> <!-- BankingApp Test -->
